### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by HIDEKAZU-YARITA** [HIDEKAZU-YARITA/furima-32479#9]
# URL
https://furima-32479.herokuapp.com/

# Basic認証のIDとパスワード
ID: administrator
PASSWORD: 22360679

# 出品者用のメールアドレスとパスワード
email: sample@sample.com
PASSWORD: sample123

# 購入者用のメールアドレスとパスワード
email: test@test.com
PASSWORD: test123

# 購入用カードの番号・期限・セキュリティコード
番号: 4242424242424242
期限: 03/23
セキュリティコード: 123

**Comment by tcamp1234** [comment]
HIDEKAZU-YARITAさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
